apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wnuwoqohc-python 
  janus-idp.io/tekton: wnuwoqohc-python
  backstage.io/kubernetes-id: wnuwoqohc-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wnuwoqohc-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml